---
- name: install lua-language-server
  command: "{{ item }}"
  with_items:
    - "curl https://github.com/LuaLS/lua-language-server/releases/download/{{ lua_ls_version }}/lua-language-server-{{ lua_ls_version }}-linux-x64.tar.gz -L -o /tmp/lua-language-server.tar.gz"
    - "tar  zxvf /tmp/lua-language-server.tar.gz -C /tmp"
    - "sudo mv /tmp/bin/lua-language-server /usr/local/bin"
    - "sudo chmod +x /usr/local/bin/lua-language-server"
