---
- name: install prettierd
  command: "{{ item }}"
  with_items:
    - "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo  -o /tmp/yarn.repo"
    - "sudo mv /tmp/yarn.repo /etc/yum.repos.d/"
    - "sudo -E rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg"
    - "dnf -y install yarn"
    - "yarn global add prettier"

- name: install ShellCheck
  dnf:
    name: "{{ item }}"
    state: installed
    enablerepo: epel
  with_items:
    - ShellCheck

- name: install shfmt
  command: "{{ item }}"
  with_items:
    - "curl https://github.com/mvdan/sh/releases/download/{{ shfmt_version }}/shfmt_{{ shfmt_version }}_linux_amd64 -L -o /tmp/shfmt_{{ shfmt_version }}_linux_amd64"
    - "sudo mv /tmp/shfmt_{{ shfmt_version }}_linux_amd64  /usr/local/bin/shfmt"
    - "sudo chmod +x /usr/local/bin/shfmt"
